# Generated by Django 5.1.1 on 2024-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default='none', max_length=1000000000000000000000000000000000000000),
        ),
    ]
